
project_id = "ibdjzzgvxlscmwlbuewd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ibdjzzgvxlscmwlbuewd.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[functions.square-checkout]
verify_jwt = false

[functions.square-payments]
verify_jwt = false

[functions.square-webhook]
verify_jwt = false

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
