// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibdjzzgvxlscmwlbuewd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZGp6emd2eGxzY213bGJ1ZXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDM0OTcsImV4cCI6MjA2NjIxOTQ5N30.RJHAWlWrVIrMEAMwd-eAZ772AaCh8ENvfqZfSNmzj40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);